Repository sayure-paiva/BC18_EcommerceHardware_front, pull requests merged in 2022-07, with the labels that each got.

#238 Correção botão dos produtos loja-empreendedor.
  src/app/empreendedor/loja-empreendedor/loja-empreendedor.component.html
Labels: bug

#239 bug carrinho
  src/app/carrinho/carrinho.component.html
  src/app/carrinho/carrinho.component.scss
  src/app/empreendedor/loja-empreendedor/loja-empreendedor.component.html
  src/app/empreendedor/loja-empreendedor/loja-empreendedor.component.scss
Labels: bug, documentation

#242 Grafic
  package-lock.json
  package.json
  src/app/admin/admin.module.ts
  src/app/admin/components/admin/admin/admin.component.html
  src/app/admin/components/admin/admin/admin.component.ts
  src/app/admin/components/edits/edits/edits.component.html
  src/app/admin/components/graficos/grafico/grafico.component.html
  src/app/admin/components/graficos/grafico/grafico.component.scss
  src/app/admin/components/graficos/grafico/grafico.component.spec.ts
  src/app/admin/components/graficos/grafico/grafico.component.ts
  src/app/admin/components/graficos/graficos/graficos.component.html
  src/app/admin/components/graficos/graficos/graficos.component.scss
  src/app/admin/components/graficos/graficos/graficos.component.spec.ts
  src/app/admin/components/graficos/graficos/graficos.component.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/config/api.config.ts
  src/app/core/services/loja/loja.service.ts
  src/app/core/services/produtos/produto.service.ts
Labels: enhancement

#243 Correções graficos
  src/app/admin/admin.module.ts
  src/app/admin/components/admin/admin/admin.component.html
  src/app/admin/components/graficos/graficoConsumidor/graficoConsumidor.component.html
  src/app/admin/components/graficos/graficoConsumidor/graficoConsumidor.component.scss
  src/app/admin/components/graficos/graficoConsumidor/graficoConsumidor.component.spec.ts
  src/app/admin/components/graficos/graficoConsumidor/graficoConsumidor.component.ts
  src/app/admin/components/graficos/graficoEmpreendedor/graficoEmpreendedor.component.html
  src/app/admin/components/graficos/graficoEmpreendedor/graficoEmpreendedor.component.scss
  src/app/admin/components/graficos/graficoEmpreendedor/graficoEmpreendedor.component.spec.ts
  src/app/admin/components/graficos/graficoEmpreendedor/graficoEmpreendedor.component.ts
  src/app/core/services/consumidor/consumidor.service.ts
  src/app/core/services/empreendedor/empreendedor.service.ts
Labels: bug, documentation, enhancement
